plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
remote_theme: just-the-docs/just-the-docs 
include:
  - LICENSE.md
  - stata.toc
  - aki_ra.pkg
  - destringerror_ra.pkg
  - datefix_ra.pkg
  - zanthro.pkg
  - aki_ra/*
  - destringerror_ra/*
  - datefix_ra/*
  - zanthro/*
