site_name: Utilities Documentation
theme:
  name: material
  features:
    - navigation.instant
    - toc.follow
    - navigation.tabs
nav:
    - Home: 'index.md'
    - 'Documentation':
        - 'AKI': 'aki_ra.md'
        - 'Datefix': 'datefix_ra.md'
        - 'Destring Error': 'destringerror_ra.md'
        - 'Zanthro': 'zanthro_ra.md'
    - About:
        - 'License': 'license.md'
        - 'Release Notes': 'release-notes.md'
repo_url: https://github.com/squidfunk/mkdocs-material
